// Generated by CoffeeScript 1.6.2
var Alarm, americano;

americano = require('americano-cozy');

module.exports = Alarm = americano.getModel('Alarm', {
  action: {
    type: String,
    "default": 'DISPLAY'
  },
  trigg: {
    type: String
  },
  description: {
    type: String
  },
  related: {
    type: Object,
    "default": null
  }
});
