// Generated by CoffeeScript 1.6.2
var Contact, americano;

americano = require('americano-cozy');

module.exports = Contact = americano.getModel('Contact', {
  fn: String,
  datapoints: [Object]
});
