// Generated by CoffeeScript 1.9.3
var Contact, americano;

americano = require('americano-cozy');

module.exports = Contact = americano.getModel('Contact', {
  fn: String,
  n: String,
  datapoints: [Object]
});
