// Generated by CoffeeScript 1.6.2
var americano;

americano = require('americano-cozy');

module.exports = {
  note: {
    all: function(note) {
      return emit(note._id, note);
    },
    path: function(note) {
      return emit(note.path, note);
    },
    tree: function(note) {
      return emit(note.parent_id, note.title);
    },
    lastmodified: function(note) {
      return emit(note.lastModificationValueOf, note);
    }
  },
  alarm: {
    all: function(doc) {
      return emit(doc._id, doc);
    }
  },
  contact: {
    all: function(doc) {
      return emit(doc._id, doc);
    }
  },
  todolist: {
    all: function(doc) {
      return emit(doc._id, doc);
    }
  },
  tree: {
    all: function(doc) {
      return emit(doc.type, doc);
    }
  },
  task: {
    all: function(doc) {
      return emit(doc._id, doc);
    }
  }
};
