// Generated by CoffeeScript 1.9.3
var Contact;

Contact = require('../models/contact');

module.exports.fetch = function(req, res, next, id) {
  return Contact.find(id, function(err, contact) {
    if (err) {
      return res.status(500).send({
        error: err
      });
    }
    if (!contact) {
      return res.status(404).send({
        error: 'Contact not found'
      });
    }
    req.contact = contact;
    return next();
  });
};

module.exports.list = function(req, res) {
  return Contact.request('all', function(err, contacts) {
    if (err) {
      return res.status(500).send({
        error: err
      });
    }
    return res.send(contacts);
  });
};

module.exports.read = function(req, res) {
  return res.send(req.contact);
};
